INSERT INTO intro_dados_ouro.maquina_clima (
	datahora,
	precipitacao,
	pressao_atm,
	radiacao,
	temperatura,
	temperatura_orvalho,
	umidade,
	vento_direcao,
	vento_rajada,
	vento_velocidade,
	uso_cpu_geral,
	uso_cpu_0,
	uso_cpu_1,
	uso_cpu_2,
	uso_cpu_3,
	uso_cpu_4,
	uso_cpu_5,
	uso_cpu_6,
	uso_cpu_7,
	frequencia_cpu,
	uso_memoria_virtual,
	uso_memoria_swap,
	bytes_lidos_disco,
	bytes_escritos_disco,
	bytes_enviados_rede,
	bytes_recebidos_rede,
	temperatura_externa,
	temperatura_chipset,
	temperatura_cpu_geral,
	temperatura_cpu_0,
	temperatura_cpu_1,
	temperatura_cpu_2,
	temperatura_cpu_3,
	temperatura_dell_cpu,
	temperatura_dell_ambiente,
	temperatura_dell_sodimm,
	temperatura_dell_gpu,
	temperatura_placa_rede,
	bateria_carga,
	bateria_carregando,
	bateria_tempo_restante
)
SELECT
	datahora,
        precipitacao,
        pressao_atm,
        radiacao,
        temperatura,
        temperatura_orvalho,
        umidade,
        vento_direcao,
        vento_rajada,
        vento_velocidade,
	uso_cpu_geral,
	uso_cpu_0,
	uso_cpu_1,
	uso_cpu_2,
	uso_cpu_3,
	uso_cpu_4,
	uso_cpu_5,
	uso_cpu_6,
	uso_cpu_7,
	frequencia_cpu,
	uso_memoria_virtual,
	uso_memoria_swap,
	bytes_lidos_disco,
	bytes_escritos_disco,
	bytes_enviados_rede,
	bytes_recebidos_rede,
	temperatura_externa,
	temperatura_chipset,
	temperatura_cpu_geral,
	temperatura_cpu_0,
	temperatura_cpu_1,
	temperatura_cpu_2,
	temperatura_cpu_3,
	temperatura_dell_cpu,
	temperatura_dell_ambiente,
	temperatura_dell_sodimm,
	temperatura_dell_gpu,
	temperatura_placa_rede,
	bateria_carga,
	bateria_carregando,
	bateria_tempo_restante
FROM intro_dados_prata.dados_meteorologicos dm
INNER JOIN (
    SELECT estampa_de_tempo,
		AVG(uso_cpu_geral) AS uso_cpu_geral,
		AVG(uso_cpu_0) AS uso_cpu_0,
		AVG(uso_cpu_1) AS uso_cpu_1,
		AVG(uso_cpu_2) AS uso_cpu_2,
		AVG(uso_cpu_3) AS uso_cpu_3,
		AVG(uso_cpu_4) AS uso_cpu_4,
		AVG(uso_cpu_5) AS uso_cpu_5,
		AVG(uso_cpu_6) AS uso_cpu_6,
		AVG(uso_cpu_7) AS uso_cpu_7,
		AVG(frequencia_cpu) AS frequencia_cpu,
		AVG(uso_memoria_virtual) AS uso_memoria_virtual,
		AVG(uso_memoria_swap) AS uso_memoria_swap,
		AVG(bytes_lidos_disco) AS bytes_lidos_disco,
		AVG(bytes_escritos_disco) AS bytes_escritos_disco,
		AVG(bytes_enviados_rede) AS bytes_enviados_rede,
		AVG(bytes_recebidos_rede) AS bytes_recebidos_rede,
		AVG(temperatura_externa) AS temperatura_externa,
		AVG(temperatura_chipset) AS temperatura_chipset,
		AVG(temperatura_cpu_geral) AS temperatura_cpu_geral,
		AVG(temperatura_cpu_0) AS temperatura_cpu_0,
		AVG(temperatura_cpu_1) AS temperatura_cpu_1,
		AVG(temperatura_cpu_2) AS temperatura_cpu_2,
		AVG(temperatura_cpu_3) AS temperatura_cpu_3,
		AVG(temperatura_dell_cpu) AS temperatura_dell_cpu,
		AVG(temperatura_dell_ambiente) AS temperatura_dell_ambiente,
		AVG(temperatura_dell_sodimm) AS temperatura_dell_sodimm,
		AVG(temperatura_dell_gpu) AS temperatura_dell_gpu,
		AVG(temperatura_placa_rede) AS temperatura_placa_rede,
		AVG(bateria_carga) AS bateria_carga,
		AVG(bateria_carregando) AS bateria_carregando,
		AVG(bateria_tempo_restante) AS bateria_tempo_restante
    FROM (
        SELECT	DATE_FORMAT(estampa_de_tempo, '%Y-%m-%d %H:00:00') AS estampa_de_tempo,
		uso_cpu_geral,
		uso_cpu_0,
		uso_cpu_1,
		uso_cpu_2,
		uso_cpu_3,
		uso_cpu_4,
		uso_cpu_5,
		uso_cpu_6,
		uso_cpu_7,
		frequencia_cpu,
		uso_memoria_virtual,
		uso_memoria_swap,
		bytes_lidos_disco,
		bytes_escritos_disco,
		bytes_enviados_rede,
		bytes_recebidos_rede,
		temperatura_externa,
		temperatura_chipset,
		temperatura_cpu_geral,
		temperatura_cpu_0,
		temperatura_cpu_1,
		temperatura_cpu_2,
		temperatura_cpu_3,
		temperatura_dell_cpu,
		temperatura_dell_ambiente,
		temperatura_dell_sodimm,
		temperatura_dell_gpu,
		temperatura_placa_rede,
		bateria_carga,
		bateria_carregando,
		bateria_tempo_restante
        FROM intro_dados_prata.info_sistema
    ) r
    GROUP BY estampa_de_tempo
) sys
ON dm.datahora = sys.estampa_de_tempo;
